eureka:
  instance:
    hostname: discovery-server
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

spring:
  cloud:
    config:
      override-system-properties: true

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER_URL:http://localhost:9411/api/v2/spans}
      connect-timeout: 1s
      read-timeout: 10s
  tracing:
    sampling:
      probability: 1.0