spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/order
    username: keshav
    password: keshav
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:org.keshav.order.kafka.OrderConfirmation
server:
  port: 8070
application:
  config:
    customer-url: http://localhost:8222/api/customers
    payment-url: http://localhost:8222/api/payments
    product-url: http://localhost:8222/api/products