spring:
  profiles:
    active: native
  application:
    name: config-server

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
      fail-fast: true

management:
  endpoints:
    web:
      exposure:
        include: health,info


server:
  port:
    8888
