server:
  port: 8060

spring:
  application:
    name: payment-service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://postgres:5432/payment
    username: keshav
    password: keshav
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: PLAINTEXT://kafka:9090
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: paymentNotificationRequest:org.keshav.payment.notification.PaymentNotificationRequest
    bootstrap-servers: PLAINTEXT://kafka:9090

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
      connect-timeout: 1s
      read-timeout: 10s
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info

